export const Urls = {
  BASE_URL_SERVER_1: "http://127.0.0.1:8000/api/",
  LOGIN: "login",
  LOGOUT: "logout",
  USER: "user",
  AUTH: "auth",
  ADMIN: "admin",
  CREATE: "create",
  EDIT: "edit",
  UPDATE: "update",
  SHOW: "show",
  DELETE: "delete",
  UPDATE_STATUS: "update-status",
  TRANSFERPOINT: "transferpoint",
  TRANSACTION_HISTORY: "transaction-history",
  TOPUP: "topup",
  LIST: "list",
  NEWS: "news",
  DETAIL: "detail",
  REWARD: "reward",
  STORE_TOKEN: "store-token",
  NOTIFICATION: "notification",
  IMG_NULL:
    "http://localhost:8000/storage/static/avatar/user/no-avatar/no-avatar.png",
};
